root = "."
tmp_dir = "logs"

[build]
  bin = "./tmp/main $SERVICE --secret=$SECRET --enable-web=false"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor","docs","web/node_modules","lambda/prebuild/nodejs/node_modules","lambda/prebuild/nodejs/dist","proto/google"]
  exclude_file = []
  exclude_regex = ["*.pb.go","*.d.ts","*pb.js"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false
