version: "3.3"

x-db: &defaults-db
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: maotrix1
    POSTGRES_USER: mcuve
    POSTGRES_DB: db

services:
  sqs:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: sqs
    ports:
      - "6001:6001"
      - "7001:7001"
    env_file: ./env/sqs.env
    volumes:
      - .:/app
    depends_on:
      - sqs-db
  iam:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: iam
    ports:
      - "6000:6000"
      - "7000:7000"
    env_file: ./env/iam.env
    volumes:
      - .:/app
    depends_on:
      - iam-db

  lambda:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: lambda
    ports:
      - "6002:6002"
      - "7002:7002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: ./env/lambda.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - lambda-db

  eventbridge:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: eventbridge
    ports:
      - "6003:6003"
      - "7003:7003"
    env_file: ./env/eb.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - eb-db

  cloudtrail:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: cloudtrail
    ports:
      - "6004:6004"
      - "7004:7004"
    env_file: ./env/eb.env
    command: 
      - "go"
      - "run"
      - "cloudtrail/listener.go"
    volumes:
      - .:/app

  iam-db:
    <<: *defaults-db
    ports: 
      - "8000:5432"
    container_name: iam-db
    volumes:
      - iam-data:/var/lib/postgresql/data

  sqs-db:
    <<: *defaults-db
    ports: 
      - "8001:5432"
    container_name: sqs-db
    volumes:
      - sqs-data:/var/lib/postgresql/data

  lambda-db:
    <<: *defaults-db
    container_name: lambda-db
    ports: 
      - "8002:5432"
    volumes:
      - lambda-data:/var/lib/postgresql/data

  eb-db:
    <<: *defaults-db
    container_name: eb-db
    ports: 
      - "8003:5432"
    volumes:
      - eb-data:/var/lib/postgresql/data


volumes:
  sqs-data:
  iam-data:
  lambda-data:
  eb-data:
