version: '3.1'

services:
  sqs:
    build: .
    ports: 
        - "6001:50051"
    env_file: 
      ./env/sqs.env
    volumes: 
        - .:/app
    depends_on: 
      - db
  iam:
    build: .
    ports: 
        - "6001:50051"
    volumes: 
        - .:/app
  
  cache:
    image: redis
    ports: 
      - "6666:6379"

  db:
    image: postgres
    restart: always
    volumes: 
      - sqs-data:/var/lib/postgresql/data 
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: maotrix1
      POSTGRES_USER: mcuve
      POSTGRES_DB: sqs


volumes: 
  sqs-data:

