version: '3.3'


x-db: &defaults-db
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: maotrix1
    POSTGRES_USER: mcuve
    POSTGRES_DB: db


services:
  sqs:
    build: .
    container_name: sqs
    ports: 
        - "6001:50051"
    env_file: 
      ./env/sqs.env
    volumes: 
        - .:/app
    depends_on: 
      - sqs-db
  iam:
    build: .
    container_name: iam
    ports: 
        - "6002:50051"
    env_file: 
      ./env/iam.env
    volumes: 
        - .:/app
    depends_on: 
      - iam-db
    
  cache:
    image: redis
    ports: 
      - "6666:6379"
    logging: 
      driver: none
  
  admin: 
    image: dpage/pgadmin4
    container_name: admin
    ports: 
      - "5050:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: mcuve@outlook.com
      PGADMIN_DEFAULT_PASSWORD: maotrix1
    logging:
      driver: none

  sqs-db:
    <<: *defaults-db
    container_name: sqs-db
    volumes: 
      - sqs-data:/var/lib/postgresql/data
  iam-db:
    <<: *defaults-db
    container_name: iam-db
    volumes: 
      - iam-data:/var/lib/postgresql/data

volumes: 
  sqs-data:
  iam-data:

